### ISSUE TITLE
xz - lmza support

### ISSUE THREAD

**Issue by doglover3920** [oe-alliance/XMLTV-Import#17]
pls. add xz - lmza support to the importer.
OpenPLi has currently added it.  Still in testing phase.
But it is the intent to supply the EPG data in compressed xz files.

Contact me on OpenPLi for the location of testfiles

https://github.com/OpenPLi/enigma2-plugin-extensions-xmltvimport/tree/master/src/EPGImport

Willy

**Comment by arn354** [comment]
hi willy,
i merged the 2 commits - what else needs to done/checked?

**Comment by doglover3920** [comment]
Checking if the lzma-backport and xz lib are loaded.
Or providing them also in the ipk.

Willy

**Comment by doglover3920** [comment]
Needed for this to run are
libc6 (>= 2.24)
liblzma5 (5.2.2-r0) 
python-lzma
