### ISSUE TITLE
Upstream changed

### ISSUE THREAD

**Issue by WanWizard** [oe-alliance/XMLTV-Import#19]
FYI: please note that the upstream repo has changed to https://github.com/OpenPLi/enigma2-plugin-extensions-epgimport. The old xmltvimport repo will no longer be maintained, and will be removed in due time.

**Comment by Schimmelreiter** [comment]
We use a fork of xmltvimport which was renamed to epgimport a while ago already.

**Comment by WanWizard** [comment]
I know that, but I see that you merge our changes in from time to time. I am just informing you that you need to look at a new repo if you want to continue doing that, als the old one is no longer maintained.
