### ISSUE TITLE
Latest PLI merge

### ISSUE THREAD

**Issue by DougMac** [oe-alliance/XMLTV-Import#28]
The latest PLI merge (2e43d64) marks a server as invalid if it doesn't have a 'LastUpdate.log' file. This file is not present on some servers so the merge has resulted in some servers no longer working.

Later commits on the PLI  branch have added a 'nocheck' attribute so that you can bypass this check if needed. Would it be possible to merge this [commit](https://github.com/OpenPLi/enigma2-plugin-extensions-epgimport/commit/88eefd24d5476ed729d53b73866b4525883a8f36)?

**Comment by RobvanderDoes** [comment]
Hmmm, that commit says "

> But we strongly recommend not to use this attribute but ensure to have the
> LastUpdate.log created once all the files are properly updated.

In other words: it's an unsafe work-around for an improper source. So not sure if it's a good idea to embed that.

**Comment by Huevos** [comment]
This is currently being worked on.

**Comment by davesayers2014** [comment]
Pull request to add here https://github.com/oe-alliance/XMLTV-Import/pull/29

**Comment by DougMac** [comment]
Thanks.
