### ISSUE TITLE
Https links do not work

### ISSUE THREAD

**Issue by jenseneverest** [oe-alliance/XMLTV-Import#37]
while http:// links work with the sources.xml
if you try to use https:// links they will not.
https: is more secure, surely they should work as well.

**Comment by nickersk** [comment]
hi, if you are using openatv 6.3 version image prior to 22.2.2018, reflash it with newer version and try again if it will work. thx

**Comment by kiddac** [comment]
This issue really could do with being fixed. Everything is moving over to https://

I hacked my own version of EPGImport.py to work for my own needs. But a better solution is probably needed. 

`	def fetchUrl(self, filename):
		if filename.startswith('http:') or filename.startswith('ftp:'):
			self.do_download(filename, self.afterDownload, self.downloadFail)
		elif filename.startswith('https:'):
			self.do_https_download(filename, self.afterDownload, self.downloadFail)
		else:
			self.afterDownload(None, filename, deleteFile=False)`

`	def do_https_download(self, sourcefile, afterDownload, downloadFail):
		path = bigStorage(9000000, '/tmp', '/media/DOMExtender', '/media/cf', '/media/mmc', '/media/usb', '/media/hdd')
		filename = os.path.join(path, 'epgimport')
		ext = os.path.splitext(sourcefile)[1]
		if ext and len(ext) < 6:
			filename += ext
		sourcefile = sourcefile.encode('utf-8')
		print>>log, "[EPGImport] Downloading: " + sourcefile + " to local path: " + filename
		response = None
		hdr = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
		 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' }
		req = urllib2.Request(sourcefile, headers=hdr)
		success = False
		try:
			response = urllib2.urlopen(req)
			with open(filename,'wb') as output:
				output.write(response.read())
				print>>log, "success"
				success = True
				self.afterDownload(True, filename)
				
		except urllib2.URLError as e:
			print>>log, (e)
			pass
			
		except:
			print>>log,"\n ***** unknown error"
			pass
		
		if not success:
			self.downloadFail(True)
		return filename`

**Comment by davesayers2014** [comment]
Has this been checked? I'm trying to download epg XML from GitHub but it won't download because of https. Thanks

**Comment by atvcaptain** [comment]
@kiddac have you update the plugin i never use this addon first time with py3 migration :)

**Comment by davesayers2014** [comment]
Has this been looked at? I'm having similar issues

**Comment by davesayers2014** [comment]
This is an example of the epg import log

`
[EPGImport] nextImport, source= Supersport-dts
[EPGImport] Downloading: http://raw.githubusercontent.com/ziko-ZR1/XML/master/dstv.xml to local path: /tmp/epgimport.xml
[EPGImport] No IPv6, using IPv4 directly: http://raw.githubusercontent.com/ziko-ZR1/XML/master/dstv.xml
[EPGImport] afterDownload /tmp/epgimport.xml
[EPGImport] unlink /tmp/epgimport.xml
[EPGImport] afterChannelDownload None
[EPGImport] Using twisted thread
[EPGImport] Parsing channels from '/etc/epgimport/custom.channels.xml'
[EPGImport] Parsing channels from '/etc/epgimport/jex.epg.channels.xml'
[XMLTVConverter] Enumerating event information
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
Unknown channel:  ginxesportshd
Unknown channel:  wwe
[EPGImport] ### thread is ready ### Events: 3934
[EPGImport] imported 3934 events
[XMLTVImport] Save last import date and count event
[XMLTVImport] Run check deep standby after import
[EPGImport] #### Finished ####
[EPGImport] nextImport, source= Supersport-dts
[EPGImport] afterDownload https://raw.githubusercontent.com/ziko-ZR1/XML/master/dstv.xml
[EPGImport] download failed: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/ziko-ZR1/XML/master/dstv.xml'
[EPGImport] imported 0 events
[XMLTVImport] Save last import date and count event
[XMLTVImport] Run check deep standby after import
[EPGImport] #### Finished ####
`

The first is using http and the second that fails is using https. 

What I don't understand is that using the http url in web browser directs to https but epg importer still downloads it.

**Comment by davesayers2014** [comment]
Changing line 187 in EPGImport.py

`if filename.startswith('http:') or filename.startswith('ftp:') or filename.startswith('https:'):`

Works for the above https GitHub example but I get this error for some sites

`[EPGImport] download failed: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')]
/usr/lib/enigma2/python/e2reactor.py:184:_doReadOrWrite
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:243:doRead
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:249:_dataReceived
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:315:dataReceived
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:235:_checkHandshakeStatus
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1915:do_handshake
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1647:_raise_ssl_error
/usr/lib/python2.7/site-packages/OpenSSL/_util.py:54:exception_from_error_queue
]`

**Comment by davesayers2014** [comment]
This works for me https://github.com/oe-alliance/XMLTV-Import/pull/50

Thanks to KiddaC for his fix

**Comment by kiddac** [comment]
I have attached a epgimport.py file that will work on python 2.7 / python 3 and dreamboxes for https urls


[EPGImport.zip](https://github.com/oe-alliance/XMLTV-Import/files/5609540/EPGImport.zip)

**Comment by atvcaptain** [comment]
merge https://github.com/oe-alliance/XMLTV-Import/commit/a848f6ea018f43a90b6924f5240e4c632992e4cf
