### ISSUE TITLE
EPGImport on Python 3.10.1

### ISSUE THREAD

**Issue by BliNeR-KeY** [oe-alliance/XMLTV-Import#66]
hello i have Problem with Python 3.10.1.

My issue ? or EPGImport need to be fixed on py3.10 ?

**Comment by Huevos** [comment]
Please tell us the issue.

**Comment by BliNeR-KeY** [comment]
> Please tell us the issue.

Download but don't compile epg.dat.
Don't compile because small epg.dat size.

I'm sure not enigma2 issue because
I extract from other box epg.dat and load from setting and works.

I think needs debug log (atm I'm using phone).

**Comment by atvcaptain** [comment]
with image, show the git from the image, at the moment no 3.10.1 images public

**Comment by BliNeR-KeY** [comment]
> with image, show the git from the image, at the moment no 3.10.1 images public

EGAMI OE-A 5.1

thats log .

`17:34:39.9640 2022-01-07 17:34:39+0100 [-] [EPGImport] ### importEvents exception: <built-in function eEPGCache_importEvents> returned a result with an exception set
`

https://github.com/oe-alliance/XMLTV-Import/blob/229b5391a4d2b3b68d5490f3868cc4da594f27f8/src/EPGImport/EPGImport.py#L405
https://github.com/oe-alliance/XMLTV-Import/blob/229b5391a4d2b3b68d5490f3868cc4da594f27f8/src/EPGImport/EPGImport.py#L431

**Comment by atvcaptain** [comment]
we cant support close source image sorry
