### ISSUE TITLE
epg offsets

### ISSUE THREAD

**Issue by kiddac** [oe-alliance/XMLTV-Import#84]
Can you add these openpli offsets commits to oe-alliance version of epg-importer.

https://github.com/OpenPLi/enigma2-plugin-extensions-epgimport/commit/e5740d5023f14aca92968a699644ebfe319ace14

**Comment by Huevos** [comment]
https://github.com/oe-alliance/XMLTV-Import/commit/00a8391e64cf201c36404bb4c09f5c66877ae318

I've imported it. Please confirm it works correctly for you.
